/**
 * ECO code → opening-name lookup.
 *
 * Covers the most commonly-encountered codes across all five families
 * (A00–E99). Codes not in this table fall back to a family description
 * via {@link ecoFamilyName}.
 *
 * Source: standard PGN/ECO classification.
 */
export const ECO_NAMES: Record<string, string> = {
  // ── A: Flank openings ────────────────────────────────────────────
  A00: 'Uncommon Opening',
  A01: 'Nimzo-Larsen Attack',
  A02: 'Bird Opening',
  A03: 'Bird Opening: Dutch Variation',
  A04: 'Reti Opening',
  A05: 'Reti Opening: KIA',
  A06: 'Reti Opening',
  A07: "King's Indian Attack",
  A08: "King's Indian Attack",
  A09: 'Reti Opening: Advance Variation',
  A10: 'English Opening',
  A11: 'English: Caro-Kann Defensive System',
  A12: 'English: Caro-Kann Defensive System',
  A13: 'English Opening',
  A14: 'English: Neo-Catalan Declined',
  A15: 'English: Anglo-Indian Defense',
  A16: 'English: Anglo-Indian Defense',
  A17: 'English: Anglo-Indian, Hedgehog',
  A18: 'English: Mikenas-Carls Variation',
  A19: 'English: Mikenas-Carls, Sicilian Variation',
  A20: 'English: King\'s English Variation',
  A21: 'English: King\'s English Variation',
  A22: 'English: King\'s English, Two Knights',
  A23: 'English: King\'s English, Bremen, Keres Variation',
  A24: 'English: King\'s English, Bremen with ...g6',
  A25: 'English: King\'s English, Closed System',
  A26: 'English: King\'s English, Botvinnik System',
  A27: 'English: King\'s English, Three Knights',
  A28: 'English: King\'s English, Four Knights',
  A29: 'English: King\'s English, Four Knights, Fianchetto',
  A30: 'English: Symmetrical Variation',
  A31: 'English: Symmetrical, Anti-Benoni',
  A32: 'English: Symmetrical, Anti-Benoni',
  A33: 'English: Symmetrical, Geller Variation',
  A34: 'English: Symmetrical Variation',
  A35: 'English: Symmetrical, Four Knights',
  A36: 'English: Symmetrical Variation',
  A37: 'English: Symmetrical, Botvinnik',
  A38: 'English: Symmetrical, Main Line',
  A39: 'English: Symmetrical, Main Line with d4',
  A40: "Queen's Pawn Game",
  A41: 'Modern Defense',
  A42: 'Modern Defense: Averbakh System',
  A43: 'Old Benoni Defense',
  A44: 'Old Benoni: Schmid Benoni',
  A45: 'Indian Game',
  A46: 'Indian Game: London System',
  A47: "Queen's Indian Defense",
  A48: "King's Indian: East Indian Defense",
  A49: "King's Indian: Fianchetto without c4",
  A50: 'Indian Game',
  A51: 'Budapest Defense',
  A52: 'Budapest Defense: Adler Variation',
  A53: 'Old Indian Defense',
  A54: 'Old Indian: Ukrainian Variation',
  A55: 'Old Indian: Main Line',
  A56: 'Benoni Defense',
  A57: 'Benko Gambit',
  A58: 'Benko Gambit: Accepted',
  A59: 'Benko Gambit: Accepted, Main Line',
  A60: 'Benoni Defense',
  A61: 'Benoni: Uhlmann Variation',
  A62: 'Benoni: Fianchetto Variation',
  A63: 'Benoni: Fianchetto, Main Line',
  A64: 'Benoni: Fianchetto, Main Line',
  A65: 'Benoni: 6.e4',
  A66: 'Benoni: Pawn Storm Variation',
  A67: 'Benoni: Taimanov Variation',
  A68: 'Benoni: Four Pawns Attack',
  A69: 'Benoni: Four Pawns, Main Line',
  A70: 'Benoni: Classical with e4 and Nf3',
  A71: 'Benoni: Classical, 8.Bg5',
  A72: 'Benoni: Classical without 9.O-O',
  A73: 'Benoni: Classical, 9.O-O',
  A74: 'Benoni: Classical, 9...a6, 10.a4',
  A75: 'Benoni: Classical with ...a6 and 10...Bg4',
  A76: 'Benoni: Classical, 9...Re8',
  A77: 'Benoni: Classical, 9...Re8, 10.Nd2',
  A78: 'Benoni: Classical with ...Nbd7 and ...Re8',
  A79: 'Benoni: Classical, 11.f3',
  A80: 'Dutch Defense',
  A81: 'Dutch Defense',
  A82: 'Dutch: Staunton Gambit',
  A83: 'Dutch: Staunton Gambit, Staunton\'s Line',
  A84: 'Dutch Defense',
  A85: 'Dutch with c4 & Nc3',
  A86: 'Dutch with g3',
  A87: 'Dutch: Leningrad, Main Variation',
  A88: 'Dutch: Leningrad, Main Variation with c6',
  A89: 'Dutch: Leningrad, Main Variation with Nc6',
  A90: 'Dutch Defense',
  A91: 'Dutch Defense',
  A92: 'Dutch Defense',
  A93: 'Dutch: Stonewall, Botvinnik Variation',
  A94: 'Dutch: Stonewall with Ba3',
  A95: 'Dutch: Stonewall',
  A96: 'Dutch: Classical Variation',
  A97: 'Dutch: Ilyin-Zhenevsky Variation',
  A98: 'Dutch: Ilyin-Zhenevsky with Qc2',
  A99: 'Dutch: Ilyin-Zhenevsky with b3',

  // ── B: Semi-Open games (1.e4 except 1...e5) ─────────────────────
  B00: 'Uncommon King\'s Pawn Opening',
  B01: 'Scandinavian Defense',
  B02: 'Alekhine Defense',
  B03: 'Alekhine Defense',
  B04: 'Alekhine Defense: Modern',
  B05: 'Alekhine Defense: Modern, Main Line',
  B06: 'Modern Defense',
  B07: 'Pirc Defense',
  B08: 'Pirc: Classical Variation',
  B09: 'Pirc: Austrian Attack',
  B10: 'Caro-Kann Defense',
  B11: 'Caro-Kann: Two Knights, 3...Bg4',
  B12: 'Caro-Kann Defense',
  B13: 'Caro-Kann: Exchange Variation',
  B14: 'Caro-Kann: Panov Attack',
  B15: 'Caro-Kann Defense',
  B16: 'Caro-Kann: Bronstein-Larsen Variation',
  B17: 'Caro-Kann: Steinitz Variation',
  B18: 'Caro-Kann: Classical Variation',
  B19: 'Caro-Kann: Classical, Spassky Variation',
  B20: 'Sicilian Defense',
  B21: 'Sicilian: Smith-Morra Gambit',
  B22: 'Sicilian: Alapin Variation',
  B23: 'Sicilian: Closed',
  B24: 'Sicilian: Closed',
  B25: 'Sicilian: Closed',
  B26: 'Sicilian: Closed, 6.Be3',
  B27: 'Sicilian Defense',
  B28: 'Sicilian: O\'Kelly Variation',
  B29: 'Sicilian: Nimzowitsch Variation',
  B30: 'Sicilian Defense',
  B31: 'Sicilian: Rossolimo Variation',
  B32: 'Sicilian Defense',
  B33: 'Sicilian Defense',
  B34: 'Sicilian: Accelerated Dragon, Exchange Variation',
  B35: 'Sicilian: Accelerated Dragon, Modern Bc4',
  B36: 'Sicilian: Accelerated Dragon, Maroczy Bind',
  B37: 'Sicilian: Accelerated Dragon, Maroczy Bind',
  B38: 'Sicilian: Accelerated Dragon, Maroczy Bind, 6.Be3',
  B39: 'Sicilian: Accelerated Dragon, Breyer Variation',
  B40: 'Sicilian Defense',
  B41: 'Sicilian: Kan Variation',
  B42: 'Sicilian: Kan, 5.Bd3',
  B43: 'Sicilian: Kan, 5.Nc3',
  B44: 'Sicilian Defense',
  B45: 'Sicilian: Taimanov Variation',
  B46: 'Sicilian: Taimanov Variation',
  B47: 'Sicilian: Taimanov (Bastrikov)',
  B48: 'Sicilian: Taimanov, English Attack',
  B49: 'Sicilian: Taimanov, Be2',
  B50: 'Sicilian Defense',
  B51: 'Sicilian: Moscow Variation',
  B52: 'Sicilian: Moscow, ...Bd7',
  B53: 'Sicilian: Chekhover Variation',
  B54: 'Sicilian Defense',
  B55: 'Sicilian: Prins, Venice Attack',
  B56: 'Sicilian Defense',
  B57: 'Sicilian: Sozin / Magnus Smith Trap',
  B58: 'Sicilian: Classical',
  B59: 'Sicilian: Classical, Boleslavsky',
  B60: 'Sicilian: Richter-Rauzer',
  B61: 'Sicilian: Richter-Rauzer, Larsen Variation',
  B62: 'Sicilian: Richter-Rauzer, 6...e6',
  B63: 'Sicilian: Richter-Rauzer Attack',
  B64: 'Sicilian: Richter-Rauzer, 7...Be7 main line',
  B65: 'Sicilian: Richter-Rauzer, 7...Be7, 9...Nxd4',
  B66: 'Sicilian: Richter-Rauzer, 7...a6',
  B67: 'Sicilian: Richter-Rauzer, 7...a6, 8...Bd7',
  B68: 'Sicilian: Richter-Rauzer, 7...a6, 9...Be7',
  B69: 'Sicilian: Richter-Rauzer, 11.Bxf6',
  B70: 'Sicilian: Dragon Variation',
  B71: 'Sicilian: Dragon, Levenfish Attack',
  B72: 'Sicilian: Dragon, Classical Attack',
  B73: 'Sicilian: Dragon, Classical, 8.O-O',
  B74: 'Sicilian: Dragon, Classical, 9.Nb3',
  B75: 'Sicilian: Dragon, Yugoslav Attack',
  B76: 'Sicilian: Dragon, Yugoslav Attack, 7...O-O',
  B77: 'Sicilian: Dragon, Yugoslav, 9.Bc4',
  B78: 'Sicilian: Dragon, Yugoslav, 10.O-O-O',
  B79: 'Sicilian: Dragon, Yugoslav, 12.h4',
  B80: 'Sicilian: Scheveningen',
  B81: 'Sicilian: Scheveningen, Keres Attack',
  B82: 'Sicilian: Scheveningen, 6.f4',
  B83: 'Sicilian: Scheveningen, Modern',
  B84: 'Sicilian: Scheveningen, Classical',
  B85: 'Sicilian: Scheveningen, Classical Main Line',
  B86: 'Sicilian: Sozin Attack',
  B87: 'Sicilian: Sozin, Fischer Variation',
  B88: 'Sicilian: Sozin, Leonhardt Variation',
  B89: 'Sicilian: Sozin, 7.Be3',
  B90: 'Sicilian: Najdorf',
  B91: 'Sicilian: Najdorf, Zagreb (Fianchetto) Variation',
  B92: 'Sicilian: Najdorf, Opocensky Variation',
  B93: 'Sicilian: Najdorf, 6.f4',
  B94: 'Sicilian: Najdorf, 6.Bg5',
  B95: 'Sicilian: Najdorf, 6.Bg5 e6',
  B96: 'Sicilian: Najdorf, 7.f4',
  B97: 'Sicilian: Najdorf, Poisoned Pawn',
  B98: 'Sicilian: Najdorf, 7...Be7',
  B99: 'Sicilian: Najdorf, 7...Be7 Main Line',

  // ── C: Open games (1.e4 e5) ─────────────────────────────────────
  C00: 'French Defense',
  C01: 'French: Exchange Variation',
  C02: 'French: Advance Variation',
  C03: 'French: Tarrasch',
  C04: 'French: Tarrasch, Guimard',
  C05: 'French: Tarrasch, Closed',
  C06: 'French: Tarrasch, Closed Main Line',
  C07: 'French: Tarrasch, Open',
  C08: 'French: Tarrasch, Open, 4.exd5 exd5',
  C09: 'French: Tarrasch, Open, Main Line',
  C10: 'French: Paulsen Variation',
  C11: 'French: Classical',
  C12: 'French: McCutcheon Variation',
  C13: 'French: Classical',
  C14: 'French: Classical, Steinitz Variation',
  C15: 'French: Winawer',
  C16: 'French: Winawer, Advance',
  C17: 'French: Winawer, Advance Variation',
  C18: 'French: Winawer, Classical',
  C19: 'French: Winawer, Advance, Poisoned Pawn',
  C20: "King's Pawn Game",
  C21: 'Center Game',
  C22: 'Center Game',
  C23: 'Bishop\'s Opening',
  C24: 'Bishop\'s Opening: Berlin Defense',
  C25: 'Vienna Game',
  C26: 'Vienna Game: Falkbeer',
  C27: 'Vienna Game: Frankenstein-Dracula',
  C28: 'Vienna Game',
  C29: 'Vienna Gambit',
  C30: "King's Gambit Declined",
  C31: "King's Gambit Declined: Falkbeer",
  C32: "King's Gambit Declined: Falkbeer, Modern",
  C33: "King's Gambit Accepted",
  C34: "King's Gambit Accepted",
  C35: "King's Gambit Accepted: Cunningham",
  C36: "King's Gambit Accepted: Modern Defense",
  C37: "King's Gambit Accepted: Quaade Gambit",
  C38: "King's Gambit Accepted: Hanstein Gambit",
  C39: "King's Gambit Accepted: Allgaier Gambit",
  C40: "King's Knight Opening",
  C41: 'Philidor Defense',
  C42: 'Russian Game (Petrov Defense)',
  C43: 'Russian Game: Modern Attack',
  C44: "King's Pawn Game",
  C45: 'Scotch Game',
  C46: 'Three Knights Opening',
  C47: 'Four Knights: Scotch Variation',
  C48: 'Four Knights: Spanish Variation',
  C49: 'Four Knights: Spanish, Symmetrical',
  C50: 'Italian Game',
  C51: 'Evans Gambit',
  C52: 'Evans Gambit',
  C53: 'Italian: Classical',
  C54: 'Italian: Classical, Greco Gambit',
  C55: 'Italian: Two Knights Defense',
  C56: 'Italian: Two Knights, Open Variation',
  C57: 'Italian: Two Knights, Fried Liver Attack',
  C58: 'Italian: Two Knights, Polerio',
  C59: 'Italian: Two Knights, Knorre Variation',
  C60: 'Ruy Lopez',
  C61: 'Ruy Lopez: Bird Variation',
  C62: 'Ruy Lopez: Old Steinitz',
  C63: 'Ruy Lopez: Schliemann Defense',
  C64: 'Ruy Lopez: Classical',
  C65: 'Ruy Lopez: Berlin Defense',
  C66: 'Ruy Lopez: Berlin, Closed',
  C67: 'Ruy Lopez: Berlin, Open',
  C68: 'Ruy Lopez: Exchange Variation',
  C69: 'Ruy Lopez: Exchange, 5.O-O',
  C70: 'Ruy Lopez: Morphy Defense',
  C71: 'Ruy Lopez: Modern Steinitz',
  C72: 'Ruy Lopez: Modern Steinitz, 5.O-O',
  C73: 'Ruy Lopez: Modern Steinitz, Alapin',
  C74: 'Ruy Lopez: Modern Steinitz, Siesta Variation',
  C75: 'Ruy Lopez: Modern Steinitz, Rubinstein',
  C76: 'Ruy Lopez: Modern Steinitz, Fianchetto',
  C77: 'Ruy Lopez: Anderssen',
  C78: 'Ruy Lopez: Closed',
  C79: 'Ruy Lopez: Steinitz Deferred',
  C80: 'Ruy Lopez: Open Variation',
  C81: 'Ruy Lopez: Open, Howell Attack',
  C82: 'Ruy Lopez: Open, Italian Variation',
  C83: 'Ruy Lopez: Open, Classical',
  C84: 'Ruy Lopez: Closed',
  C85: 'Ruy Lopez: Exchange, Bronstein',
  C86: 'Ruy Lopez: Worrall Attack',
  C87: 'Ruy Lopez: Closed, Averbakh',
  C88: 'Ruy Lopez: Closed',
  C89: 'Ruy Lopez: Marshall Attack',
  C90: 'Ruy Lopez: Closed',
  C91: 'Ruy Lopez: Closed, Bogoljubow',
  C92: 'Ruy Lopez: Closed, Flohr Variation',
  C93: 'Ruy Lopez: Closed, Smyslov Defense',
  C94: 'Ruy Lopez: Closed, Breyer Defense',
  C95: 'Ruy Lopez: Closed, Breyer Defense Main Line',
  C96: 'Ruy Lopez: Closed, Borisenko Variation',
  C97: 'Ruy Lopez: Closed, Chigorin Defense',
  C98: 'Ruy Lopez: Closed, Chigorin, 12...Nc6',
  C99: 'Ruy Lopez: Closed, Chigorin, 12...c5d4',

  // ── D: Closed games (1.d4 d5) ───────────────────────────────────
  D00: "Queen's Pawn Game",
  D01: 'Richter-Veresov Attack',
  D02: "Queen's Pawn Game",
  D03: 'Torre Attack',
  D04: "Queen's Pawn Game",
  D05: 'Colle System',
  D06: "Queen's Gambit",
  D07: "Queen's Gambit Declined: Chigorin",
  D08: 'Albin Counter-Gambit',
  D09: 'Albin Counter-Gambit',
  D10: 'Slav Defense',
  D11: 'Slav: Quiet Variation',
  D12: 'Slav: Exchange',
  D13: 'Slav: Exchange Variation',
  D14: 'Slav: Exchange, Symmetrical',
  D15: 'Slav: Three Knights',
  D16: 'Slav: Alapin Variation',
  D17: 'Slav: Czech Defense',
  D18: 'Slav: Dutch Variation',
  D19: 'Slav: Dutch Variation, Main Line',
  D20: "Queen's Gambit Accepted",
  D21: "QGA: 3.Nf3",
  D22: "QGA: Alekhine Defense",
  D23: "QGA: Mannheim Variation",
  D24: "QGA: Bogoljubow Defense",
  D25: "QGA: 4.e3",
  D26: "QGA: Classical",
  D27: "QGA: Classical, 6.O-O",
  D28: "QGA: Classical, 7.Qe2",
  D29: "QGA: Classical, Smyslov Variation",
  D30: "Queen's Gambit Declined",
  D31: 'QGD: 3.Nc3',
  D32: 'QGD: Tarrasch',
  D33: 'QGD: Tarrasch, Schlechter-Rubinstein',
  D34: 'QGD: Tarrasch, Prague',
  D35: 'QGD: Exchange Variation',
  D36: 'QGD: Exchange, Positional Line',
  D37: 'QGD: 4.Nf3',
  D38: 'QGD: Ragozin Defense',
  D39: 'QGD: Ragozin, Vienna Variation',
  D40: 'QGD: Semi-Tarrasch',
  D41: 'QGD: Semi-Tarrasch, 5.cxd5',
  D42: 'QGD: Semi-Tarrasch, 7.Bd3',
  D43: 'Semi-Slav Defense',
  D44: 'Semi-Slav: Botvinnik Variation',
  D45: 'Semi-Slav: 5.e3',
  D46: 'Semi-Slav: 6.Bd3',
  D47: 'Semi-Slav: Meran',
  D48: 'Semi-Slav: Meran, Old Main Line',
  D49: 'Semi-Slav: Meran, Reynolds Variation',
  D50: 'QGD: Modern Variation',
  D51: 'QGD: 5.Bg5',
  D52: 'QGD: Cambridge Springs Defense',
  D53: 'QGD: Lasker Defense',
  D54: 'QGD: Anti-Neo-Orthodox',
  D55: 'QGD: Anti-Neo-Orthodox',
  D56: 'QGD: Lasker Defense',
  D57: 'QGD: Lasker Defense, Main Line',
  D58: 'QGD: Tartakower Variation',
  D59: 'QGD: Tartakower, Main Line',
  D60: 'QGD: Orthodox Defense',
  D61: 'QGD: Orthodox, Rubinstein Attack',
  D62: 'QGD: Orthodox, Rubinstein, 7...c5',
  D63: 'QGD: Orthodox, Capablanca Variation',
  D64: 'QGD: Orthodox, Rubinstein Attack',
  D65: 'QGD: Orthodox, Rubinstein Attack, Main Line',
  D66: 'QGD: Orthodox, Bd3 line',
  D67: 'QGD: Orthodox, Bd3, Capablanca freeing maneuver',
  D68: 'QGD: Orthodox, Classical Variation',
  D69: 'QGD: Orthodox, Classical, 13.dxe5',
  D70: 'Neo-Grünfeld Defense',
  D71: 'Neo-Grünfeld, 5.cxd5',
  D72: 'Neo-Grünfeld, 5.cxd5 main line',
  D73: 'Neo-Grünfeld with Nf3',
  D74: 'Neo-Grünfeld, 6.cxd5',
  D75: 'Neo-Grünfeld, Classical with e3',
  D76: 'Neo-Grünfeld, 6.cxd5 Nxd5, 7.O-O',
  D77: 'Neo-Grünfeld, 6.O-O',
  D78: 'Neo-Grünfeld, 6.O-O c6',
  D79: 'Neo-Grünfeld, 6.O-O c6, Main Line',
  D80: 'Grünfeld Defense',
  D81: 'Grünfeld: Russian, Byrne Variation',
  D82: 'Grünfeld: 4.Bf4',
  D83: 'Grünfeld: Grünfeld Gambit',
  D84: 'Grünfeld: Grünfeld Gambit Accepted',
  D85: 'Grünfeld: Exchange',
  D86: 'Grünfeld: Exchange, Classical',
  D87: 'Grünfeld: Exchange, Spassky Variation',
  D88: 'Grünfeld: Spassky, Main Line',
  D89: 'Grünfeld: Spassky, Main Line, 13.Bd3',
  D90: 'Grünfeld: Three Knights',
  D91: 'Grünfeld: 5.Bg5',
  D92: 'Grünfeld: 5.Bf4',
  D93: 'Grünfeld: 5.Bf4 with e3',
  D94: 'Grünfeld: Smyslov Defense',
  D95: 'Grünfeld: Botvinnik Variation',
  D96: 'Grünfeld: Russian Variation',
  D97: 'Grünfeld: Russian, Hungarian',
  D98: 'Grünfeld: Russian, Smyslov',
  D99: 'Grünfeld: Russian, Smyslov, Main Line',

  // ── E: Indian defenses ──────────────────────────────────────────
  E00: 'Catalan Opening / Indian',
  E01: 'Catalan: Closed',
  E02: 'Catalan: Open, 5.Qa4+',
  E03: 'Catalan: Open, Alekhine Variation',
  E04: 'Catalan: Open, 5.Nf3',
  E05: 'Catalan: Open, Classical',
  E06: 'Catalan: Closed, 5.Bf4',
  E07: 'Catalan: Closed, Botvinnik',
  E08: 'Catalan: Closed, Main Line with Qc2',
  E09: 'Catalan: Closed, Main Line',
  E10: "Queen's Pawn Game",
  E11: 'Bogo-Indian Defense',
  E12: "Queen's Indian Defense",
  E13: "Queen's Indian: 4.Nc3 Bb7, 5.Bg5",
  E14: "Queen's Indian: 4.e3",
  E15: "Queen's Indian: 4.g3",
  E16: "Queen's Indian: Capablanca Variation",
  E17: "Queen's Indian: Old Main Line, 7.Nc3",
  E18: "Queen's Indian: Old Main Line, 7.Nc3 Ne4",
  E19: "Queen's Indian: Old Main Line, 9.Qxc3",
  E20: 'Nimzo-Indian Defense',
  E21: 'Nimzo-Indian: Three Knights',
  E22: 'Nimzo-Indian: Spielmann Variation',
  E23: 'Nimzo-Indian: Spielmann, 4...c5',
  E24: 'Nimzo-Indian: Sämisch Variation',
  E25: 'Nimzo-Indian: Sämisch, Keres Variation',
  E26: 'Nimzo-Indian: Sämisch, O\'Kelly',
  E27: 'Nimzo-Indian: Sämisch, 5...O-O',
  E28: 'Nimzo-Indian: Sämisch, 5.e3',
  E29: 'Nimzo-Indian: Sämisch, Main Line',
  E30: 'Nimzo-Indian: Leningrad Variation',
  E31: 'Nimzo-Indian: Leningrad, Main Line',
  E32: 'Nimzo-Indian: Classical',
  E33: 'Nimzo-Indian: Classical, 4...Nc6',
  E34: 'Nimzo-Indian: Classical, Noa Variation',
  E35: 'Nimzo-Indian: Classical, 5.cxd5',
  E36: 'Nimzo-Indian: Classical, Botvinnik',
  E37: 'Nimzo-Indian: Classical, San Remo',
  E38: 'Nimzo-Indian: Classical, 4...c5',
  E39: 'Nimzo-Indian: Classical, Pirc',
  E40: 'Nimzo-Indian: 4.e3',
  E41: 'Nimzo-Indian: 4.e3 c5',
  E42: 'Nimzo-Indian: 4.e3 c5, 5.Ne2',
  E43: 'Nimzo-Indian: Fischer Variation',
  E44: 'Nimzo-Indian: Fischer, 5.Ne2',
  E45: 'Nimzo-Indian: 4.e3, Bronstein',
  E46: 'Nimzo-Indian: 4.e3 O-O',
  E47: 'Nimzo-Indian: 4.e3 O-O, 5.Bd3',
  E48: 'Nimzo-Indian: 4.e3 O-O, 5.Bd3 d5',
  E49: 'Nimzo-Indian: 4.e3, Botvinnik System',
  E50: 'Nimzo-Indian: 4.e3 e8g8, 5.Nf3',
  E51: 'Nimzo-Indian: 4.e3, Main Line',
  E52: 'Nimzo-Indian: 4.e3, Main Line with ...b6',
  E53: 'Nimzo-Indian: 4.e3 c5, 5.Nf3',
  E54: 'Nimzo-Indian: 4.e3, Gligoric',
  E55: 'Nimzo-Indian: 4.e3, Gligoric, Bronstein',
  E56: 'Nimzo-Indian: 4.e3, Main Line with 7...Nc6',
  E57: 'Nimzo-Indian: 4.e3, Main Line with 8...dxc4',
  E58: 'Nimzo-Indian: 4.e3, Main Line with 8...Bxc3',
  E59: 'Nimzo-Indian: 4.e3, Main Line, 10...cxd4',
  E60: "King's Indian Defense",
  E61: "King's Indian: 3.Nc3",
  E62: "King's Indian: Fianchetto",
  E63: "King's Indian: Fianchetto, Panno",
  E64: "King's Indian: Fianchetto, Yugoslav",
  E65: "King's Indian: Fianchetto, Yugoslav 7.O-O",
  E66: "King's Indian: Fianchetto, Yugoslav with c5",
  E67: "King's Indian: Fianchetto, Classical",
  E68: "King's Indian: Fianchetto, Classical Main Line",
  E69: "King's Indian: Fianchetto, Classical Main Line",
  E70: "King's Indian: 4.e4",
  E71: "King's Indian: Makogonov",
  E72: "King's Indian with e4 and g3",
  E73: "King's Indian: Averbakh",
  E74: "King's Indian: Averbakh, 6...c5",
  E75: "King's Indian: Averbakh, Main Line",
  E76: "King's Indian: Four Pawns Attack",
  E77: "King's Indian: Four Pawns, 6.Be2",
  E78: "King's Indian: Four Pawns, 6.Be2",
  E79: "King's Indian: Four Pawns, Main Line",
  E80: "King's Indian: Sämisch",
  E81: "King's Indian: Sämisch, 5...O-O",
  E82: "King's Indian: Sämisch, double fianchetto",
  E83: "King's Indian: Sämisch, 6...Nc6",
  E84: "King's Indian: Sämisch, Panno",
  E85: "King's Indian: Sämisch, Orthodox",
  E86: "King's Indian: Sämisch, Orthodox, 7.Nge2 c6",
  E87: "King's Indian: Sämisch, Orthodox",
  E88: "King's Indian: Sämisch, Orthodox, 7...exd4",
  E89: "King's Indian: Sämisch, Orthodox Main Line",
  E90: "King's Indian: 5.Nf3",
  E91: "King's Indian: 6.Be2",
  E92: "King's Indian: Classical",
  E93: "King's Indian: Petrosian System",
  E94: "King's Indian: Orthodox",
  E95: "King's Indian: Orthodox, 7...Nbd7, 8.Re1",
  E96: "King's Indian: Orthodox, 7...Nbd7, Main Line",
  E97: "King's Indian: Mar del Plata",
  E98: "King's Indian: Mar del Plata, 9.Ne1",
  E99: "King's Indian: Mar del Plata, Main Line",
};

const FAMILY: Record<string, string> = {
  A: 'Flank Opening',
  B: 'Semi-Open Game',
  C: 'Open Game',
  D: 'Closed Game',
  E: 'Indian Defense',
};

/** Friendly family name for a single ECO letter. */
export function ecoFamilyName(letter: string): string | null {
  return FAMILY[letter.toUpperCase()] ?? null;
}

/**
 * Look up an opening name. Falls back to the family description when an
 * exact code isn't in the table; returns null only for codes outside A–E.
 */
export function ecoName(eco: string): string | null {
  if (!eco) return null;
  const code = eco.trim().toUpperCase();
  if (ECO_NAMES[code]) return ECO_NAMES[code];
  const fam = ecoFamilyName(code[0]);
  return fam;
}
